<?php

namespace FOS\UserBundle\Repository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {
       $this->createQueryBuilder('u')
           ->where('u.username = :username ')
           ->setParameter ('username',$username)
           ->getQuery()
           ->getOneOrNullResult();
    }
}
